% File: <nrCimCheckFEAInterface.m>
%
% Syntax: nrCimCheckFEAInterface(FEAInterfaceFile,NRCIMDatabase)
%
% Description:
%       Checks an FEAInterfaceFile against an NRCIM database to see if all
%       nodal positions and coordinate systems are as expected.  If not,
%       the MFR database cannot be used with that FEA file.
%
% Input Parameters:
%       FEAInterfaceFile - this file is generated from the FEA model by
%       running the script generated by nrCimCreateFeaDataScript
%
%       NRCIMDatabase - the NRCIM .mat database file created by running
%       nrCimInit
%
% Output Parameters:
%       none
%
% Required Global Data Structures:
%       CST (loaded internally)
%
% Required Data Files:
%       none
%       

%
% Extended Documentation (Won't be shown in Matlab help command)
%

%
% Revision History
%
% $Id: 
%
% INDENT-OFF*
% INDENT-ON*


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%           Herzberg Institute of Astrophysics                  %%%%%
%%%%%%      Astronomy Technology Research Group - Victoria           %%%%%
%
% (c) <2010>                          (c) <2010>
% National Research Council           Conseil national de recherches
% Ottawa, Canada, K1A 0R6             Ottawa, Canada, K1A 0R6
% All rights reserved                 Tous droits reserves
%                               
% NRC disclaims any warranties,       Le CNRC denie toute garantie
% expressed, implied, or statu-       enoncee, implicite ou legale,
% tory, of any kind with respect      de quelque nature que se soit,
% to the software, including          concernant le logiciel, y com-
% without limitation any war-         pris sans restriction toute
% ranty of merchantability or         garantie de valeur marchande
% fitness for a particular pur-       ou de pertinence pour un usage
% pose.  NRC shall not be liable      particulier.  Le CNRC ne
% in any event for any damages,       pourra en aucun cas etre tenu
% whether direct or indirect,         responsable de tout dommage,
% special or general, consequen-      direct ou indirect, particul-
% tial or incidental, arising         ier ou general, accessoire ou
% from the use of the software.       fortuit, resultant de l'utili-
%                                     sation du logiciel.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function nrCimCheckFEAInterface(FEAInterfaceFile,MFRDatabase)

FEAData = load(FEAInterfaceFile);
load(MFRDatabase);

error_flag = 0;

for ii=1:CST.Num
    for jj=1:CST.Meta(ii).NumNodes
        nodenum = CST.Meta(ii).NodeNums(jj);
        NdLstIdx = CST.Meta(ii).NdLstStart+(jj-1);
        FEALstPos = FEAData(NdLstIdx,2:4);
        MALstPos = MA.NodeLst(NdLstIdx,2:4);
        if ~isequal(FEALstPos,MALstPos)
            fprintf('\n\nError: Node %d position difference\n',nodenum);
            fprintf('\tFEA List Pos: %.3f,%.3f,%.3f\n',FEALstPos(1:3));
            fprintf('\tMA List Pos: %.3f,%.3f,%.3f\n',MALstPos(1:3));
            err_flag = 1;
        end
        % Find out if the orientation of the node matches the CST in Matlab
        % First get the CST from FEA data. This is in the G coordinate
        % system
        FEARotZ = FEAData(NdLstIdx,5);
        FEARotX = FEAData(NdLstIdx,6);
        FEARotY = FEAData(NdLstIdx,7);
        FEARot = vlCsMult(vlCsRotZ(FEARotZ),vlCsRotX(FEARotX),vlCsRotY(FEARotY));
        FEARot=FEARot(:,1:3);
        % Now get the CST from NRCIM, in the G coordinate system
        NRCIMRot = vlCsMult(vlCsInv(CST.ZG),CST.ZC(:,:,ii));
        NRCIMRot = NRCIMRot(:,1:3);
        
        RotDiff = FEARot-NRCIMRot;
        if ~all(all(RotDiff < 1e-6))
            fprintf('\n\nError: Node rotation does not match CST, Node=%d, CSTIdx = %d\n',nodenum,ii);
            fprintf('\tFEA Rotation Matrix\n');
            FEARot
            fprintf('\tNRCIM Rotation Matrix\n');
            NRCIMRot
            fprintf('\tDifference\n');
            Difference = FEARot-NRCIMRot
            error_flag = 1;
        end
    end
end

if error_flag == 0
    fprintf('Pass: FEA interface matches - FEA file can be used with this MFR database\n');
else
    error('FEA Interface does not match - cannot use this MFR database with FEA file');
end